require.config({
  baseUrl:'/',
  paths:{
    'jquery':'/libs/jquery/jquery-3.4.1.min',
    'header':'/js/modules/header',
    'footer':'/js/modules/footer',
    'banner':'/libs/jquery-plugins/spotlight.bundle',
    'list':'/js/list',
    'template':'libs/art-template/template-web',
    'detail':'/js/detail'
  },
  shim:{
    'banner':{
      deps:['jquery']
    }
  }
})